# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Deploy New Version

on: workflow_dispatch
#on:
#  push:
#    tags:
#      - 'v*'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 9
      uses: actions/setup-java@v1
      with:
        java-version: 9
    - name: GPG Setup
      env:
        GPG_KEY_BASE64: ${{ secrets.GPG_KEY_BASE64 }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      run: ./gpg-setup.sh
    - name: Deploy to OSS Sonatype
      env:
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      # mvn -Prelease source:jar javadoc:jar deploy -Dgpg.passphrase=thephrase
      run: mvn -B -Prelease source:jar javadoc:jar deploy --file pom.xml -s settings-template.xml -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}

  deploy-jdk8:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: GPG Setup
      env:
        GPG_KEY_BASE64: ${{ secrets.GPG_KEY_BASE64 }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      run: ./gpg-setup.sh
    - name: Deploy to OSS Sonatype
      env:
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      # mvn -Prelease source:jar javadoc:jar deploy -Dgpg.passphrase=thephrase
      run: mvn -B -Prelease source:jar javadoc:jar deploy --file pom-jdk8.xml -s settings-template.xml -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}
